// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2jZ5qmYgunCUeAX4bOKeyYdt1ErittpU',
    appId: '1:596687975293:web:dd53d5807892fb54849214',
    messagingSenderId: '596687975293',
    projectId: 'entrega1-app-moviles',
    authDomain: 'entrega1-app-moviles.firebaseapp.com',
    storageBucket: 'entrega1-app-moviles.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbdnJ-J1nQbfMuvNlBeL2gy-3NC3ovOxA',
    appId: '1:596687975293:android:0fb19b66f204f499849214',
    messagingSenderId: '596687975293',
    projectId: 'entrega1-app-moviles',
    storageBucket: 'entrega1-app-moviles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB--OcxAEySDL4teqEF9Jsocl0Z1D6JVVM',
    appId: '1:596687975293:ios:d8bfe764c4967c93849214',
    messagingSenderId: '596687975293',
    projectId: 'entrega1-app-moviles',
    storageBucket: 'entrega1-app-moviles.appspot.com',
    iosBundleId: 'com.example.entrega1AppsMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB--OcxAEySDL4teqEF9Jsocl0Z1D6JVVM',
    appId: '1:596687975293:ios:d8bfe764c4967c93849214',
    messagingSenderId: '596687975293',
    projectId: 'entrega1-app-moviles',
    storageBucket: 'entrega1-app-moviles.appspot.com',
    iosBundleId: 'com.example.entrega1AppsMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2jZ5qmYgunCUeAX4bOKeyYdt1ErittpU',
    appId: '1:596687975293:web:236fd84f7dee1272849214',
    messagingSenderId: '596687975293',
    projectId: 'entrega1-app-moviles',
    authDomain: 'entrega1-app-moviles.firebaseapp.com',
    storageBucket: 'entrega1-app-moviles.appspot.com',
  );
}

